### ISSUE TITLE
KeyError for empty BNB balance

### ISSUE THREAD

**Issue by tcdewit** [sQu1rr/binance-dust-sweeper#1]
When the users BNB balance is empty, account.py won't add BNB to the coins dictionary, resulting in a KeyError in function has_bnb(). A possible solution is to check for the presence of the BNB key:  

```
def has_bnb(self):
        return ('BNB' in self.coins) and (self.coins['BNB']['balance'] > 0)
```

**Comment by sQu1rr** [comment]
makes sense, will fix. I'm thinking to initialise all base coins balance (bnb, usdt, etc) to 0, since it's not the first time i can see this kind of issue.
