### ISSUE TITLE
Additional commandline option for base coins

### ISSUE THREAD

**Issue by tcdewit** [sQu1rr/binance-dust-sweeper#4]
I personally only use ETH as base coin, but i wouldn't mind converting my dust into BNB or BTC if thats more profitable. Perhaps it's good to have two commandline options?   
- one for determining the base coins that shouldn't be dusted (in my case ETH)   
- one for determining the base coins that can be used for exchanging dust into (in my case ETH, BNB and BTC)

**Comment by sQu1rr** [comment]
did you try using "-p eth,bnb,btc" - it will ignore base coins and suggest the conversion into these coins.

**Comment by tcdewit** [comment]
You're right... that does the trick :)
