### ISSUE TITLE
Request for clarification 

### ISSUE THREAD

**Issue by Asdrubale90** [sQu1rr/binance-dust-sweeper#9]
I'm sorry for the question "stupid": I have a fraction of altcoin worth 5 dollars that at the time binance does not allow to recover even with bnb. From your example I noticed that you used coins that binance somehow allows you to recover even the fractions. If binance on my altcoin allows me only unit exchanges, with your software could I recover them or I'm just fooling myself and I have to wait for news from official developers?

**Comment by sQu1rr** [comment]
you cannot recover them, simply get rid of them. so in your case you will lose 5 dollars using this script
